Gitignore
The issue here is that the .sif file is stuck on the git ignore, I have been trouble shooting but I cannot find a solution this also means that I cannot do anything to push it as the .sif is too large for me to push as 500mb
I had to reaction to the creation of the add-gitignore but I could see it was a new branch
add-gitignore ⚡ was added to my kernel
My name was incorrect it was change in my pc to R.gitinore.txt that was a mistake on my part
lastly for the commit that was fine and then for the pushing I also had to write the downstream branch which was
└[~/Downloads]> git push --set-upstream origin add-gitignore
once again however I cannot push it. I will show you the error here as was mentioned before here is the error I have gotten for over an hour at the time or writing this Enumerating objects: 15, done.
Counting objects: 100% (15/15), done.
Delta compression using up to 8 threads
Compressing objects: 100% (13/13), done.
Writing objects: 100% (15/15), 456.07 MiB | 4.39 MiB/s, done.
Total 15 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), done.
remote: error: Trace: e15204f6c072dd5ad60afcbc4d264676965972166cb3d71d83c315f885f99f3e
remote: error: See https://gh.io/lfs for more information.
remote: error: File assignment.sif is 450.29 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
To github.com:al-chari/Vasileios-Theocharis-Assingment-1.git
 ! [remote rejected] add-gitignore -> add-gitignore (pre-receive hook declined)
error: failed to push some refs to 'github.com:al-chari/Vasileios-Theocharis-Assingment-1.git'


As for the logs I did use simply git log however I was trying to finish everything so I could explain the git log case and point here is the log before this was commited: commit 4c59bac03c794f1ad0bf0800427a49360ab5e257 (HEAD -> add-gitignore)
Author: vasilis <butchillas@protonmail.com>
Date:   Sat Jan 31 00:50:35 2026 +0100

    .gitgnore

commit 24921466896c305599336791bc1559b482bb5c8a (main)
Author: vasilis <butchillas@protonmail.com>
Date:   Sat Jan 31 00:38:35 2026 +0100

    question 7

commit 3d9e7c9a31d42d72ba16a70c32dbd703df0f57a6 (origin/main)
Author: vasilis <butchillas@protonmail.com>
Date:   Sat Jan 31 00:10:49 2026 +0100

    Add files

commit 26b25a0a305ae3cdb7cdadaa398cf2f85d3c0b5d
Author: al-chari <butchillas@protonmail.com>
Date:   Sat Jan 31 00:06:08 2026 +0100

    Create file
(END)


 I originally wrote everything in docker but it crashed on both my laptop and PC not sure why to be honest I know you are not the type of man to be merciful with me here I respect that and I hold only appreciation for people who are strict with the rules, I just need to express that I am not stupid I am understand the assignment and it is not even a matter of time simply a matter of luck in this case with my computers both not wanting to run docker and my laptop specifically bricking when I tried.